spring:
  security:
    oauth2:
      client:
        provider:
          nextjs:
            issuer-uri: http://localhost:9090
            authorization-uri: http://localhost:9090/oauth2/authorize
            token-uri: http://localhost:9090/oauth2/token
#            user-info-uri: http://localhost:9090/oauth2/userinfo

        registration:
          nextjs:
            provider: nextjs
            client-id: nextjs
            client-secret: nextjs123
            authorization-grant-type:
              - authorization_code
            scope:
              - openid
              - profile
              - email
            redirect-uri: http://localhost:8000/login/oauth2/code/nextjs
            client-authentication-method:
              - client_secret_post
              - client_secret_basic
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Request-Headers
        - SaveSession
      routes:
        - id: media-route
          uri: lb://media-service
          predicates:
            - Path=/images**
          filters:
            - TokenRelay=
            - RewritePath=/image/(?<segment>.*),/api/v1/images/${segment}
            - RewritePath=/images,/api/v1/images

        - id: identity-route
          uri: lb://identity-service
          predicates:
            - Path=/identity/**
          filters:
            - TokenRelay=
            - RewritePath=/identity/(?<segment>.*),/$\{segment}

        - id: nextjs
          uri: http://localhost:3000
          predicates:
            - Path=/**