spring:
  security:
    oauth2:
      client:
        provider:
          nextjs:
            issuer-uri: http://localhost:9090
            authorization-uri: http://localhost:9090/oauth2/authorize
            token-uri: http://localhost:9090/oauth2/token
#            user-info-uri: http://localhost:9090/oauth2/userinfo
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

        registration:
          google:
            client-id: 905661943124-sojsd3iv15a849s92rh08pdc52u3ambi.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8000/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
          nextjs:
            provider: nextjs
            client-id: nextjs
            client-secret: nextjs123
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
            redirect-uri: http://localhost:8000/login/oauth2/code/nextjs
            client-authentication-method: client_secret_post
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Request-Headers
        - SaveSession
      routes:
        - id: media-route
          uri: lb://media-service
          predicates:
            - Path=/api/v1/images/**
          filters:
            - TokenRelay=
            - RewritePath=/api/v1/images/(?<segment>.*),/api/v1/images/$\{segment}

        - id: identity-route
          uri: lb://identity-service
          predicates:
            - Path=/identity/**
          filters:
            - TokenRelay=
            - RewritePath=/identity/(?<segment>.*),/$\{segment}

        - id: nextjs
          uri: http://localhost:3000
          predicates:
            - Path=/**