spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true

minio:
  url: ${MINIO_URL}
  secret-key: ${MINIO_SECRETE_KEY}
  bucket-name: ${MINIO_BUCKET}
  access-key: ${MINIO_ACCESS_KEY}

media:
  #media endpoint
  image-end-point: ${IMAGE_ENDPOINT}

  video-end-point: ${VIDEO_ENDPOINT}

  #the host that handle show image
  base-uri: ${MEDIA_BASE_URI}

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /
  api-docs:
    path: /v3/api-docs